FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script to the working directory
COPY trigger.py .

# Install cron
RUN apt-get update && apt-get install -y cron

# Copy the crontab file and set permissions
COPY crontab /etc/cron.d/simple-cron
RUN chmod 0644 /etc/cron.d/simple-cron

# Apply the cron job
RUN crontab /etc/cron.d/simple-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
